version: "3.8"

services:
  logging-mongodb:
    image: mongo:latest
    container_name: logging-mongodb
    ports:
      - "27019:27017"

  logging-service:
    build: .
    container_name: logging-service
    ports:
      - "8009:8009"
    environment:
      - MONGODB_URL=mongodb://logging-mongodb:27017/logging_db
    depends_on:
      - logging-mongodb
